SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE Pokemon_moves;
TRUNCATE TABLE Pokemon_teams;
TRUNCATE TABLE Teams;

TRUNCATE TABLE Tournaments;
TRUNCATE TABLE Players;
TRUNCATE TABLE Pokemons;
TRUNCATE TABLE Moves;
TRUNCATE TABLE Items;
TRUNCATE TABLE Abilities;

SET FOREIGN_KEY_CHECKS = 1;